

#ifndef __PLUGIN_BINDINGS_H_
#define __PLUGIN_BINDINGS_H_

/* Generated with cbindgen:0.13.2 */

/* DO NOT EDIT This file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

typedef struct Client Client;

/**
 * Creates a logging client that writes to kafka. Configuration parameters will be located in the
 * 'kafka' section in the suricata.yaml
 */
Client *create_logging_client(const void *conf);

/**
 * Releases the logging client
 */
void release_logging_client(Client *client);

/**
 * Copy the message into our memory space and forward to the logging client
 */
int send_to_logging_client(const char *buffer, int buffer_len, Client *client);

#endif /* __PLUGIN_BINDINGS_H_ */
